### ISSUE TITLE
0.2.5 + master (2a535fb2): duplicated `findpython/__version__.py` entries in generated .whl archive

### ISSUE THREAD

**Issue by kloczek** [frostming/findpython#21]
`installer` module is sensitive about such issues and it fails like below
```console
+ /usr/bin/python3 -sBm installer dist/findpython-0.2.5-py3-none-any.whl --destdir /home/tkloczko/rpmbuild/BUILDROOT/python-findpython-0.2.5-2.fc35.x86_64
Traceback (most recent call last):
  File "/usr/lib64/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib64/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/lib/python3.8/site-packages/installer/__main__.py", line 98, in <module>
    _main(sys.argv[1:], "python -m installer")
  File "/usr/lib/python3.8/site-packages/installer/__main__.py", line 94, in _main
    installer.install(source, destination, {})
  File "/usr/lib/python3.8/site-packages/installer/_core.py", line 109, in install
    record = destination.write_file(
  File "/usr/lib/python3.8/site-packages/installer/destinations.py", line 207, in write_file
    return self.write_to_fs(scheme, path_, stream, is_executable)
  File "/usr/lib/python3.8/site-packages/installer/destinations.py", line 167, in write_to_fs
    raise FileExistsError(message)
FileExistsError: File already exists: /home/tkloczko/rpmbuild/BUILDROOT/python-findpython-0.2.5-2.fc35.x86_64/usr/lib/python3.8/site-packages/findpython/__version__.py
```
Here is content of the .whl:
```console
[tkloczko@pers-jacek findpython-0.2.5]$ unzip -l dist/findpython-0.2.5-py3-none-any.whl
Archive:  dist/findpython-0.2.5-py3-none-any.whl
  Length      Date    Time    Name
---------  ---------- -----   ----
     4966  01-01-2016 00:00   findpython-0.2.5.dist-info/METADATA
       90  01-01-2016 00:00   findpython-0.2.5.dist-info/WHEEL
       57  01-01-2016 00:00   findpython-0.2.5.dist-info/entry_points.txt
     1075  01-01-2016 00:00   findpython-0.2.5.dist-info/licenses/LICENSE
     1928  01-01-2016 00:00   findpython/__init__.py
     2564  01-01-2016 00:00   findpython/__main__.py
       22  01-01-2016 00:00   findpython/__version__.py      <<<<=== here
       22  01-01-2016 00:00   findpython/__version__.py      <<<<=== here
     6667  01-01-2016 00:00   findpython/finder.py
      442  01-01-2016 00:00   findpython/pep514tools/__init__.py
      254  01-01-2016 00:00   findpython/pep514tools/__main__.py
     6567  01-01-2016 00:00   findpython/pep514tools/_registry.py
     4638  01-01-2016 00:00   findpython/pep514tools/environment.py
      846  01-01-2016 00:00   findpython/providers/__init__.py
     1058  01-01-2016 00:00   findpython/providers/asdf.py
     1823  01-01-2016 00:00   findpython/providers/base.py
      759  01-01-2016 00:00   findpython/providers/macos.py
      662  01-01-2016 00:00   findpython/providers/path.py
     1249  01-01-2016 00:00   findpython/providers/pep514.py
     1072  01-01-2016 00:00   findpython/providers/pyenv.py
      913  01-01-2016 00:00   findpython/providers/rye.py
     6364  01-01-2016 00:00   findpython/python.py
     4374  01-01-2016 00:00   findpython/utils.py
     2010  01-01-2016 00:00   findpython-0.2.5.dist-info/RECORD
---------                     -------
    50422                     24 files
```

**Comment by kloczek** [comment]
And `build` output:
```console
+ /usr/bin/python3 -sBm build -w --no-isolation
* Getting build dependencies for wheel...
* Building wheel...
 - Adding .pdm-build/findpython-0.2.5.dist-info/METADATA -> findpython-0.2.5.dist-info/METADATA
 - Adding .pdm-build/findpython-0.2.5.dist-info/WHEEL -> findpython-0.2.5.dist-info/WHEEL
 - Adding .pdm-build/findpython-0.2.5.dist-info/entry_points.txt -> findpython-0.2.5.dist-info/entry_points.txt
 - Adding .pdm-build/findpython-0.2.5.dist-info/licenses/LICENSE -> findpython-0.2.5.dist-info/licenses/LICENSE
 - Adding src/findpython/__init__.py -> findpython/__init__.py
 - Adding src/findpython/__main__.py -> findpython/__main__.py
 - Adding .pdm-build/findpython/__version__.py -> findpython/__version__.py
 - Adding src/findpython/__version__.py -> findpython/__version__.py
/usr/lib64/python3.8/zipfile.py:1517: UserWarning: Duplicate name: 'findpython/__version__.py'     <<<<==== here
  return self._open_to_write(zinfo, force_zip64=force_zip64)
 - Adding src/findpython/finder.py -> findpython/finder.py
 - Adding src/findpython/pep514tools/__init__.py -> findpython/pep514tools/__init__.py
 - Adding src/findpython/pep514tools/__main__.py -> findpython/pep514tools/__main__.py
 - Adding src/findpython/pep514tools/_registry.py -> findpython/pep514tools/_registry.py
 - Adding src/findpython/pep514tools/environment.py -> findpython/pep514tools/environment.py
 - Adding src/findpython/providers/__init__.py -> findpython/providers/__init__.py
 - Adding src/findpython/providers/asdf.py -> findpython/providers/asdf.py
 - Adding src/findpython/providers/base.py -> findpython/providers/base.py
 - Adding src/findpython/providers/macos.py -> findpython/providers/macos.py
 - Adding src/findpython/providers/path.py -> findpython/providers/path.py
 - Adding src/findpython/providers/pep514.py -> findpython/providers/pep514.py
 - Adding src/findpython/providers/pyenv.py -> findpython/providers/pyenv.py
 - Adding src/findpython/providers/rye.py -> findpython/providers/rye.py
 - Adding src/findpython/python.py -> findpython/python.py
 - Adding src/findpython/utils.py -> findpython/utils.py
 - Adding findpython-0.2.5.dist-info/RECORD -> findpython-0.2.5.dist-info/RECORD
Successfully built findpython-0.2.5-py3-none-any.whl
```

**Comment by kloczek** [comment]
Looks like all what needs to be done is remove ` src/findpython/__version__.py` from git repo.

**Comment by frostming** [comment]
fixed on the latest release

**Comment by kloczek** [comment]
Thank you 👍
